### ISSUE TITLE
Erreur dmpy 

### ISSUE THREAD

**Issue by Mirgarr** [Sysys242/DMDPY#5]
Salut ça me dit ça c normal?

c:\Users\Mirgar\Downloads\DMDPY-main\DMDPY-main\modules\logger.py:841: SyntaxWarning: invalid escape sequence '\ '
  Center.XCenter("""
Traceback (most recent call last):
  File "c:\Users\Mirgar\Downloads\DMDPY-main\DMDPY-main\main.py", line 1, in <module>
    from modules.features import get_features
  File "c:\Users\Mirgar\Downloads\DMDPY-main\DMDPY-main\modules\features.py", line 1, in <module>      
    from logics.member_scrapper       import scrapping_task
  File "c:\Users\Mirgar\Downloads\DMDPY-main\DMDPY-main\logics\member_scrapper.py", line 1, in <module>
    from modules.utils import Utils
  File "c:\Users\Mirgar\Downloads\DMDPY-main\DMDPY-main\modules\utils.py", line 3, in <module>
    from tls_client      import Session
  File "C:\Users\Mirgar\AppData\Local\Programs\Python\Python312\Lib\site-packages\tls_client\__init__.py", line 15, in <module>
    from .sessions import Session
  File "C:\Users\Mirgar\AppData\Local\Programs\Python\Python312\Lib\site-packages\tls_client\sessions.py", line 5, in <module>
    from .settings import ClientIdentifiers
  File "C:\Users\Mirgar\AppData\Local\Programs\Python\Python312\Lib\site-packages\tls_client\settings.py", line 1, in <module>
    from typing_extensions import Literal, TypeAlias
ModuleNotFoundError: No module named 'typing_extensions'

**Comment by Mirgarr** [comment]
close pas stp
